### ISSUE TITLE
Finish calender

### ISSUE THREAD

**Issue by Blanku-cloud** [sitechtimes/club-attendence-frontend#6]

**Comment by EricWeng23** [comment]
I finished the calendar for this application where we decided to utilize the vcalendar npm package. The documentation for the vcalendar is at 'https://vcalendar.io/getting-started/installation.html'. The attributes were used to pass in the meetingDates and clubName to remind the user of the upcoming events and is displayed in highlighted blue and popover. The component is called NewCalendar.vue and is displayed once the seagull button on the upper right corner of the route /club is clicked.

**Comment by EricWeng23** [comment]
The component is called NewCalendar.vue and is displayed once the seagull button on the upper right corner of the ClubView.vue is clicked.
